spring:
  h2:
    console:
      enabled: true # H2 Console 사용 여부
      path: /h2     # Context path 변경
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL 변경
  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
